### ISSUE TITLE
⚠️TRADE OFFER⚠️🧂🤝🦞

### ISSUE THREAD

**Issue by 23ouh423** [lobster-dao/overview#11]
### ⚠️TRADE OFFER⚠️
# 🧂Salty Loot 🤝 Lobster NFT 🦞

### What is Salty Loot? 
> Salty Loot bags contain randomized nautical gear and treasure dredged up from the depths. Any bag you grab is randomly generated and stored immutably on chain. Other properties and functions are intentionally omitted for anyone to interpret. Feel free to use however you want.
![sloot8888](https://user-images.githubusercontent.com/67194517/136657651-fd394577-8a45-4777-87d3-96d8f77c8112.gif)

### Why Salty Loot? 
Inspired by Lobsters NFT and Loot Project, Salty Loot is a fun experiment in creating a new, nautical-themed loot bag which contains a weapon, armor, headgear, waist, 2x spells and 2x treasures. Animations are included with the addition of a standardised gold shimmer effect on the text and unique, randomised wave patterns.

### How Salty Loot?
For the first 48 hours:
- 6751 allo to Lobster NFT holders
- 1000 allo to Loot NFT holders
- 500 allo to CryptoPunks NFT holders
- 500 allo to BAYC NFT holders

ALL will be free to mint and ALL unclaimed Salty Loots after 48 hours will be unlocked for anyone to mint, so qualified addresses should claim asap or get rekt. There is a limit of 2 claims per 0x for Loot/Punk/Ape holders to encourage wider distribution. Some extra randomization is also implemented to prevent users from easily gaming to mint rares. 

### Offer
Following deployment and OpenSea profile setup, the smart contract ownership and 7.5% royalty distribution can be set to the Lobster DAO multisig in exchange for 20-80 LOBS NFT. 

### Vote
👍 <s>80</s> 40 LOBS
❤️ <s>70</s> 35 LOBS
🎉 <s>60</s> 30 LOBS
😄 <s>50</s> 25 LOBS
🚀 <s>40</s> 20 LOBS
😕 <s>30</s> 15 LOBS
👀 <s>20</s> 10 LOBS
👎 <s>10</s> 5 LOBS

https://twitter.com/Salty_Loot

Questions and feedback welcome!

**Comment by AZtztk** [comment]
Sure, it's made for fun, possibly additional fee source for DAO too, while creating an opportunity to encourage development of new projects for acquisition by DAO. Alternative offers/proposals also welcome.

**Comment by aasinghal** [comment]
10 at best. There are just too many loot projects hardly offering anything new.

**Comment by AZtztk** [comment]
thx @aasinghal i edited the original vote to turn the salty emojis into productive assets haha, there is now an option in 5s from 40 to 5 LOBS

**Comment by tsarpaul** [comment]
This sounds like shit. Is this how 100 IQs ask for free money nowadays?

**Comment by AZtztk** [comment]
You heard it here first, folks. LOBS. IS. MONEY. 
😂

**Comment by kkkrackpot** [comment]
With all my respect and gratitude to the offer I must note so far I don't see much of original novelty in the project.

Endless spin-offs of successful projects like loot/punks/apes/etc. may well be fun and interesting for NFT degens, but it's not the way Lobster DAO should go.

I wish good luck to the project and hope it will get some good lobsters interested, but I will vote against the offer.

**Comment by jnptzl** [comment]
Voting against. I don't see much demand for this type of derivatives yet, other loot projects derivatives are trending to 0. I would gladly vote in favor in case that changes, or at least we see a dapp being built that would use it as a primitive.

**Comment by MioQuispe** [comment]
> It's great to see this kind of enthusiasm from armchair critics who only see what is explicitly in front of them instead of imagining what could be, instead of having fun, instead of encouraging experimentation.
> 
> It costs me to make this more than I would earn from receiving some Lobster NFTs in return which I wouldn't even sell. Meanwhile Lobster DAO would earn revenue from trading fees of the Salty Loot.
> 
> This has been offered at practically donation rate in the spirit of just having fun, so would love an explanation of why you would expect some earth shattering innovation which changes the trajectory of humanity over the next trillion years here.
> 
> Sure it's not Elon Musk making a new rocket but it would still be a helpful resource to the community in how this specific project is built as it has some qualities which have not been implemented in such a combination previously, plus the code makes it simpler operationally to produce such NFTs through some quality improvements inside.
> 
> What does it look like when someone makes the effort to build something here? Does that look encouraging to anyone else who might want to add to the value of the community in their own unique ways?
> 
> Think about that.
> 
> It's not about how to deploy some DAO NFTs here, it's about encouraging builders to contribute.

Literally just copy pasting something existing. The lobsters are loot themselves already. No need for this trash.

**Comment by AZtztk** [comment]
Arm. Chair. Critic.
Cannot. See. Beyond. Own. Keyboard. And. Preconceptions.
You don't know what's been done inside the contract to make certain innovations possible, yet you continue to consider your criticisms, which are devoid of any practically useful suggestions, to be of value in any way.
