### ISSUE TITLE
Idea: Use SafeSnap

### ISSUE THREAD

**Issue by IvanGBi** [lobster-dao/overview#12]
Somebody made the first proposal to enable SafeSnap feature by Gnosis, which makes sure that snapshot votes have technical force on what the multisig can do. I fully support it and voted YES. [LINK HERE TO VOTE](https://snapshot.org/#/10b57e6da0.eth/proposal/QmcBbWQqydi4aBcYBwhRc8WRwuJzx2W236HQK1jzyBsAHT)

**Comment by Swader** [comment]
Voted in. Close?

**Comment by IvanGBi** [comment]
Somebody needs to implement it now?

**Comment by lebed2045** [comment]
I've create the proposal, and if there's not better candidate can implement it as well. but I need to coordinate it with someone from admins. Will ping admins
