### ISSUE TITLE
LOBS Analytics

### ISSUE THREAD

**Issue by msirinotis** [lobster-dao/overview#17]
**Context:**
As mentioned in the chat by Ivan, the DAO will hold back from minting unclaimed LOBS (to save gas).
Because of this it is assumed that OpenSea and the likes will only pick up the traits & rarity of the current supply and not include the (large portion) of the DAO's NFT's.

**Proposal:**
This is a short proposal to generate analytics on the full set of the 6751 available LOBS.

I will generate for the full list of LOBS;
- Holder Address
- Image Link
- Rarity (%) of all traits
- Rarity Score
- Relative Rarity Ranking

See the below screenshot for an example of another collection;
![image](https://user-images.githubusercontent.com/78072083/136864707-12a6ed41-b0e4-4825-aaa7-89d4b5723e72.png)

Will also group the rarity score's by address so we can rank each address/member :1st_place_medal: 

**How:**
I'll parse the raw JSON metadata of all LOBS and provide the code & a spreadsheet of the above (that we can re-run adhoc).
Holders will be able to filter down to their address and see the data across multiple LOBS.

**Payment:**
I missed the bot claim by a few hours & DM'd days before the mint (before we saw the value..) and I want one of these fancy fucking crab claws an irrational amount. This is my way of giving back something to get one.
So, 1 LOB from the treasury (my unclaimed one) for this.

It's likely this doesn't pass before Wednesday's reveal (let's be honest, I'll do the work anyway) but there is the issue of if this passes what LOB do I get?
I'd like to keep it completely random.
We can say that I get the direct next available LOBS id or even just do a random number generator of the DAO LOBS.. if a big brain has a better solution to randomise all the better.

**Pros:**
- Community building / hype for reveal
- Find out who has the biggest horseshoe
- See if Ivan gmi or ngmi
- Pray that some 3 post anon doesn't get the diamond claw together
- I will likely add more analytics to this in the future
- Keep track of flippers so we can bring out the guillotine 
- See how much good art the DAO is sitting on

**Cons:**

- 1 LOB cost - given from treasury to community member.

**Action:**

- Post feedback if you want this to happen
- If enough interest, then we can make a snapshot

**Comment by Fortuno89** [comment]
I support doing this, 1 LOBs is a fair pay for this job.

**Comment by msirinotis** [comment]
> Good idea, fully support it. Let's brainstorm what else can you @msirinotis do for community smirk Write a post, Sir after you do analytics.

Yeah, this is a good idea. I'll do a write up too.

**Comment by degen92** [comment]
idea is pretty good but is this a good way to donate 🦞,, need to brainstorm what comes next like somebody missed and will again ask for it using whatever 😬 buts its a good part community building but i would rather ask to eth giveaways

**Comment by msirinotis** [comment]
I won't comment on the value as I just want this to be about having fun and doing something for the community. The vote can decide if it's worthy or not.

Zhongfu kindly posted the ipfs locations & traits earlier so I've been working with those already.

Some pre-processing _so far_ rather than just taking pure rarity.


- Add combination trait -> if has both custom artwork & signature (only 2....  rare)
- Preliminary weightings on different traits (we care way more about artwork/signature than mood)
- Condense typo's for 'untextured' gene's.
- Penalise Earth Circle 01, 06, 11 etc genes as they are common amongst each other

![image](https://user-images.githubusercontent.com/78072083/136887941-1408516a-5fe0-4cd1-944f-8b21103ca0f2.png)

Some of highest ranking LOBS so far;
The 2 art+signature combinations.
![image](https://user-images.githubusercontent.com/78072083/136888059-b5ca5fb8-a0f3-4ceb-ab30-0c116ea3ef53.png)
![image](https://user-images.githubusercontent.com/78072083/136888642-71caeb18-7d43-43a5-a7e8-c36f58e7f41a.png)

A rare non-signed piece
![image](https://user-images.githubusercontent.com/78072083/136888725-52d925b2-093f-4898-ba4b-31d546d8dca2.png)

Rare non-artwork piece
![image](https://user-images.githubusercontent.com/78072083/136888905-10b3ae4e-d193-4a78-9741-4cdb1c96001a.png)

A... not so rare piece
![image](https://user-images.githubusercontent.com/78072083/136890229-8ace6e01-25df-4024-b24b-934be27500e8.png)

Upcoming work;
- Adjustments to ranking algorithm in line with lobsters values over pure rarity.
- Map all holders to the traits/ranking data once ID's are revealed.

**Comment by edisonljh** [comment]
Love the idea - am in support.

**Comment by Fortuno89** [comment]
I second what etthiscam posted, I dont think this is worth the actual market price of Lobs (3 eth atm). Seems too expensive and I have already seen rarity ranks posted on chats.

I also think the DAO should hold off for some time to distribute unclaimed lobsters, dont find it prudent to start using them so early tbh

**Comment by paolo-farellon** [comment]
Agree on this.

**Comment by msirinotis** [comment]
Ok, the snapshot period is over.

[https://snapshot.org/#/10b57e6da0.eth/proposal/Qmaua3zenAJRHbDaLyxuv7giP1uAeXHu2Y6iibKr7mct8J](https://snapshot.org/#/10b57e6da0.eth/proposal/Qmaua3zenAJRHbDaLyxuv7giP1uAeXHu2Y6iibKr7mct8J)

Firstly, thank you to all that voted and for such a high percentage of you voting to accept the proposal.

Given that the standardising governance issue is still under discussion - **what are the next steps here?**

Keep in mind this is meant to be as random as feasibly possible. I know there are constraints that now we know the VRF seed we know which token_id will be minted next but is there a way around this? DAO mints next 5-10 and we run a random number generator? Spit-balling here.

**Comment by degenETH** [comment]
Looks good ser

**Comment by tartakovsky** [comment]
This one was resolved, the man finally got his LOBS. Closing.
