### ISSUE TITLE
Genesis Shards

### ISSUE THREAD

**Issue by tushar7-arch** [lobster-dao/overview#29]
Got in touch with the Genesis Shards team, they are interested in partnering with LobsterDAO too 

They hold pre-IDOs for tokens through NFT sharding giving them access to multiple DeFi + NFT projects 

Need inputs on how we can beneficially use the same 

1. LobsterHR contribution for projects that require people from LobsterDAO as per need
2. Allocation(for DAO) as per project basis, this can enable the DAO to invest early in certain projects at even seed stage 
3. Allocation on the gen-shards access to invest in pre-IDOs for the members(?) 
4. Access to liquidity mining, staking programs for their projects 
5. LobsterDAO NFT holders can get a call with the gen-shards team to hold pre-IDOs 
6. Access to momentum6 for investement pitching for NFT holders 
7.(?) 

Requesting more ideas for a mutually beneficial partnership for the same 

Will help close the partnership if the proposal goes through when floated

**Comment by alex-core-0x** [comment]
> 
> 
> > That's AA idea 👍. Lobster DAO could also provide the feedback on project's pitch deck and other materials, propose ideas for suitable partnerships.
> 
> Thank you ser, please put in your name to be in the point of contact group

In my original post. Edited it.
