### ISSUE TITLE
Discussion: Non-Ethereum projects

### ISSUE THREAD

**Issue by gas1cent** [lobster-dao/overview#39]
A lot is happening outside of the Ethereum ecosystem. I know we've never explicitly sworn loyalty to Ethereum, just want to see if there is interest in alternative chains at all.

What do you think about pursuing projects on other chains and trying to make deals with them?

Pros:
- More projects to partner with
- Lower transaction fees might increase participation
- We might attract additional testers looking to invest in a certain chain, ex: Arbitrum airdrop miners
- Generally good for the industry, encourages diversification and competition

Cons:
- Already hard to keep track of news and events in one ecosystem
- Further fragmentation
- The learning curve, need to install new wallets, sync nodes, use bridges, etc

There really are 2 questions
1) Do you think we should look into other chains at this stage?
2) If yes, what chains? We can vote and focus on 2-3 most popular.

**Comment by tartakovsky** [comment]
The answer seems to be "why not?". People can look wherever they like. If there is something interesting going on outside of ethereum and a person can negotiate some mutually beneficial relationship – why not, we'll consider it. Closing.
