### ISSUE TITLE
Discussion: VC DAO

### ISSUE THREAD

**Issue by tartakovsky** [lobster-dao/overview#40]
So the VC DAO idea has been popping up many times. Let's argue about it here and provide all the arguments and counter arguments in one place. 

The idea is that the DAO's funds can be used to invest into projects, e.g. buying pre-sales and whatever.

Let's debate.

**Comment by Pivomansu** [comment]
everything goes to the fact that in the near future the DAO will be forced to register as a legal entity. Therefore, it is obvious what risks this carries and I doubt that community members will agree to accept such risks. There would probably be a more effective model for creating a pitch desk, so that startups can present their projects on discord and can find Angle investments or advising from members of the Lobster DAO.

**Comment by kkkrackpot** [comment]
> everything goes to the fact that in the near future the DAO will be forced to register as a legal entity. 

Why exactly the DAO "will be forced to register as a legal entity"? What is that 'everything' exactly?
Personally, I don't see anything what would make someone think so.
Neither I will support any activity what can require the DAO to go through any legal shit like that. (not to mention that personally I'm against the VC/ICO/etc. idea at all, even anonymously)

**Comment by Pivomansu** [comment]
Under the new project crypto regulations in EU, DAO will be equivalent to the entity. I mean it`s only project but who knows how it`ll proceed. In any case, as long as the Lobs DAO remains a unifying community structure, and not a money-making company, we are not in danger
I`m also against Lobs DAO as VC actually:)

**Comment by kkkrackpot** [comment]
> Under the new project crypto regulations in EU, DAO will be equivalent to the entity. I mean it`s only project but who knows how it`ll proceed. In any case, as long as the Lobs DAO remains a unifying community structure, and not a money-making company, we are not in danger I`m also against Lobs DAO as VC actually:)

EU regulation is EU's problem. US regulation is US problem. Vanuatu regulation is Vanuatu's problem, etc. They can go try to enforce it somehow, their right. 
But I dont see why the DAO should bother with all that 'regulation' shit.

**Comment by tartakovsky** [comment]
Okay, I don't see any support for this or ongoing debate. Closing.
