### ISSUE TITLE
New Logo & Branding 

### ISSUE THREAD

**Issue by Youssefsooska** [lobster-dao/overview#49]
There been a logo discussion over the past months but i was busy back then‚ 
I would like to contribute with a branding design regarding the lobster logo and the lobster nft and any future plans‚
If that subject still up i would like to get a few answers regarding the direction of the branding matter to start working on the task

These question consisting of several matters **;tldr this is a brief** 

*Contents below described with images included with every style*

1-Logo values and desired style ([Monogram](https://cryptologos.cc/logos/oax-oax-logo.png?v=014), [Wordmarks](![image](https://user-images.githubusercontent.com/96180861/146182564-bbeb5e16-e021-4070-aac9-eb67c4383d0f.png)), [Pictorial marks (symbol)](https://cryptologos.cc/logos/uniswap-uni-logo.svg?v=014), [Abstract mark](https://cryptologos.cc/logos/cardano-ada-logo.svg?v=014), [Mascot](https://cryptologos.cc/logos/pancakeswap-cake-logo.svg?v=014), [Combination mark (a combined wordmark and pictorial mark, abstract mark, or mascot)](https://cryptologos.cc/logos/bitcore-btx-logo.svg?v=014) or [Emblem](https://cryptologos.cc/logos/exchange-union-xuc-logo.png?v=014))

2-Colors ([Solid](https://www.pantone.com/media/wysiwyg/fashion-color-trend-report-spring-2017-colors-mobile.jpg)) regarding the color characteristic or [Gradient](https://cdn.logojoy.com/wp-content/uploads/20190718163447/How-To-Design-a-Gradient-Logo-01.png) 

3-Typography (for future usage in product design)

that's it for now, further questions will be applied after approval of the proposal.

if you have any questions or suggestions regarding the proposal feel free you are welcomed

Thank you all for your time.

**Comment by amplice** [comment]
Hi Autismvisky,

This is an interesting proposal, and I think there could be support from the community for this.

First things though, do you have a portfolio of previous work available? Generally when I've worked with designers they will send a portfolio of their best stuff so we can gauge their style, vibe, etc.

I'm assuming that you yourself are a designer here. If you are not a designer, then I'd suggest you propose the method you will use to procure a logo/branding designs.

Either way, I think the community would find this interesting, but a bit more detail would be helpful before proceeding

Cheers

amp

**Comment by amplice** [comment]
Hi @Youssefsooska,

We discussed in the working group a bit and I think the general consensus is we don't really need new branding right now

Appreciate you suggesting it and if you're interested I think right now there are some other ways to contribute to the DAO if that's something you're interested in.

**Comment by kkkrackpot** [comment]
The branding idea is good, overall.
But personally I think right now it's still too early to implement it. We have to put our "product" on steady track first -- and then make branding for it.

**Comment by Youssefsooska** [comment]
Hi amp and kkkrackpot
Sorry for responding this late
I really appreciate you guys took the time discussing the matter in the work group and i appreciate your response‚ with that being said i am happily available whenever my knowledge fit you.

In the meantime while you are working on putting the product on steady track and i wish you the best in this matter‚

Ofc I would like to contribute to the DAO whenever i get the chance‚ 

you got my dribbble and behance portfolio so feel free to contact me whenever you feel i am fit for the task

Thank you again guys and Merry Christmas to you and the community

Cheers
