### ISSUE TITLE
Dune Analytics Dashboard

### ISSUE THREAD

**Issue by phfr** [lobster-dao/overview#51]
Due to requests in chat I built a Dune analytics dashboard for Lobsterdao.

The current state is available at https://dune.xyz/kwizzles/LobsterDAO

I am glad for any input one what to change add and to maintain this long term.

The possibility of a Lobster as compensation was mentioned in chat ( https://t.me/lobsters_chat/311771 ) and I'd be happy to receive one and to further finetune and improve the dashboard according to community feedback.

As said before, feel free to drop me any ideas for further improvements

**Comment by akashspl** [comment]
great work :)

**Comment by cryptographicas** [comment]
Hey Philip this is great, well done ser dashboard looks 10/10

**Comment by phfr** [comment]
Thanks again to everybody who voted!
I will do my best to maintain this in the future and also improve it!

**Comment by NerosBerg** [comment]
Hi, can you add stats for the Mood trait when you have the time? 

It's the third rarest trait in the whole collection as per:
https://datastudio.google.com/u/0/reporting/3ae1eb51-4dbb-4899-b264-31e3156c624e/page/M0rcC

**Comment by phfr** [comment]
done
