### ISSUE TITLE
Lobsterdao 3D | Seashells | 10b57e6 fa5h10N

### ISSUE THREAD

**Issue by saszer** [lobster-dao/overview#52]
![ezgif-7-bb8a0bdde6](https://user-images.githubusercontent.com/43649755/147894822-7b27e626-c005-4ac9-8da6-0e65c04e826e.gif)

**Context:** 
I recently released an interactive 3D visualiser for Lobster NFT's, made during the EthGlobal hackathon. 'Seashells' , Generating unique 3D version of each lobsterdao NFT. 

You can try it at (play on PC) : **https://seashells.embracingearth.space/,**  
alt link: https://worldsz.github.io/Seashells_10b57e6/ 

Lobster NFT got released and had proper analytics sheets which caught my eye at the same time I was experimenting around this idea of 3D visualiser for 2D NFT's and they all fell together. At a Macro level, the project showcases the integration of NFT's in a game engine by different API systems, IPFS databases and wrapping of thousands of 2D NFT's to thousands of their corresponding unique 3D versions. 

For Lobs Community:

- Adds another infinity to Lobster NFT's infinite glory!
- Gives you a lot more unique and 3D variations of pfp's/gifs of your same NFT.
- Showcased LobsterDao at [EthGlobal ](https://twitter.com/ETHGlobal/status/1463572938091900933)
- Provides a base Project for all 6751 unique 3D interactive lobsters in some future integration with any Metaverse game like protocols.

**Request:** 
I've been a long member of Lobster community as  sz , initially, I was obligated to get 3 drops, my wallet also got hacked amidst submission and claim and things didn't go straight. I would like to propose a proposal for 0, 1, 2 or 3 (creating proposals) Lobs.
I Kind of had a product-first approach here, and a fun project I wanted to try on.
If it's worthy of the request or not, is for the lobster community to decide, I thought it's worth a try and hence here it is :)

**Pros and Cons:** 
_Pros:_ 
Some of these are already mentioned in the context section and that'll stay going forward such as AN AWESOME 3D VERSION of your NFT, as a version of the project is already up and out there and some has happened like showcasing LobsterDao to a global community at EthGlobal Hackathon. Furthermore in conjunction of my request: 
- Encourages more projects/individuals/ideas to build with LobsterDao in unique ways. 'Building' - IMO, a bit different to using lobs for airdrops and access.
- Might be a start to something :)
- A good use and release of extra stuck lobs.
- Adds another member with a Lobs pfp (3d)

_Cons:_
- Loss of Lobs from the treasury to a contributing community member.
- I can finally verify and enter Lobs discord kingdom

Extra acknowledgement: Thanking msirinotis #17 and the lobster community for passing that as that work has informed this one and uses that analytics sheet as a database refrence.

**Comment by karakan43** [comment]
looks dope!

**Comment by saszer** [comment]
anyone shy on commenting just react 👍 or 👎...

**Comment by Pivomansu** [comment]
looks dope ser! I believe you deserved seafood!

**Comment by IvanGBi** [comment]
super cool, wow, would vote YES to reward the legend

**Comment by ncerovac** [comment]
snapshot for voting is live, go and vote Lobs! https://snapshot.org/#/10b57e6da0.eth/proposal/0x968e65c183dcf1062bfd56b98f4dfb2d366bd4bc3099e590c3f8645d44fd9a6d

**Comment by gas1cent** [comment]
The easiest vote ever 😄  Stunning job @saszer!

**Comment by saszer** [comment]
Thank you, everyone! Awesome seafam at Lobs! 

ref:
https://twitter.com/10b57e6da0/status/1480502851436691457
https://twitter.com/10b57e6da0/status/1483560236371828743
